<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-14T03:09:42Z" name="My Allure Suite" finished-at="2021-06-14T03:09:42Z" duration-ms="194">
    <groups>
    </groups>
    <test started-at="2021-06-14T03:09:42Z" name="Allure Tests" finished-at="2021-06-14T03:09:42Z" duration-ms="194">
      <class name="allure.examples.MyFirstClass">
        <test-method signature="myFirstTest()[pri:0, instance:allure.examples.MyFirstClass@66c83fc8]" started-at="2021-06-14T03:09:42Z" name="myFirstTest" finished-at="2021-06-14T03:09:42Z" duration-ms="46" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTest -->
      </class> <!-- allure.examples.MyFirstClass -->
      <class name="allure.examples.MyCalculatorTest">
        <test-method signature="tc1()[pri:0, instance:allure.examples.MyCalculatorTest@546621c4]" started-at="2021-06-14T03:09:42Z" name="tc1" description="TC 1 : This test adds two numbers" finished-at="2021-06-14T03:09:42Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method signature="tc2()[pri:0, instance:allure.examples.MyCalculatorTest@546621c4]" started-at="2021-06-14T03:09:42Z" name="tc2" description="TC 2 : This test subtracts two numbers" finished-at="2021-06-14T03:09:42Z" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method signature="tc3()[pri:0, instance:allure.examples.MyCalculatorTest@546621c4]" started-at="2021-06-14T03:09:42Z" name="tc3" description="TC 3 : This test multiplies two numbers" finished-at="2021-06-14T03:09:42Z" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method signature="tc4()[pri:0, instance:allure.examples.MyCalculatorTest@546621c4]" started-at="2021-06-14T03:09:42Z" name="tc4" description="TC 4 : This test divides two numbers" finished-at="2021-06-14T03:09:42Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6.0] but found [5.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6.0] but found [5.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at allure.examples.MyCalculatorTest.tc4(MyCalculatorTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc4 -->
      </class> <!-- allure.examples.MyCalculatorTest -->
    </test> <!-- Allure Tests -->
  </suite> <!-- My Allure Suite -->
</testng-results>
